version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: voice-chat-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/code
      - MAX_AUDIO_QUEUE_SIZE=50
      - TTS_START_ENGINE=orpheus
      - TTS_ORPHEUS_MODEL=freds0/orpheus-brspeech-3b-0.1-ft-32bits-GGUF
      - DIRECT_STREAM=true
      - LANGUAGE=pt
    volumes:
      # Mount models directory for persistent storage
      - ./models:/app/models
      - ./data:/app/data
    networks:
      - voice-chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./nextjs-voice-chat
      dockerfile: Dockerfile
    container_name: voice-chat-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - voice-chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  voice-chat-network:
    driver: bridge

volumes:
  models:
  data: